using System;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Threading;

namespace GamingThroughVoiceRecognitionSystem.Views
{
    public partial class MainWindow : Window
    {
        private bool isMaximized = false;
        private DispatcherTimer voiceTimer;

        // Path to command txt (generated by vosk exe)
        private readonly string voiceCommandFile = @"voice_command.txt";

        // Path to your OFFLINE Vosk EXE
        private readonly string voskExePath =
            @"D:\new changing model of project\GamingThroughVoiceRecognition-Updated-main\vosk\dist\voice_listener.exe";

        // Keep listener alive globally
        private static Process voskProcess = null;

        public MainWindow()
        {
            InitializeComponent();
            SetupButtonAnimations(LoginButton);
            SetupButtonAnimations(SignUpButton);
            SetupButtonAnimations(CloseButton);
            SetupButtonAnimations(MinimizeButton);
            SetupButtonAnimations(MaximizeButton);

            this.Closed += Window_Closed;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            StartVoskListener();
            StartVoiceMonitor();
        }

        // ------------------------------------------------------------
        // START OFFLINE VOSK LISTENER (.exe)
        // ------------------------------------------------------------
        private void StartVoskListener()
        {
            try
            {
                if (voskProcess != null && !voskProcess.HasExited)
                    return;    // already running

                if (!File.Exists(voskExePath))
                {
                    MessageBox.Show("Vosk listener EXE not found:\n" + voskExePath);
                    return;
                }

                var psi = new ProcessStartInfo
                {
                    FileName = voskExePath,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };

                voskProcess = new Process();
                voskProcess.StartInfo = psi;

                voskProcess.OutputDataReceived += (s, e) =>
                {
                    if (!string.IsNullOrEmpty(e.Data))
                        Console.WriteLine("[VOSK] " + e.Data);
                };

                voskProcess.ErrorDataReceived += (s, e) =>
                {
                    if (!string.IsNullOrEmpty(e.Data))
                        Console.WriteLine("[VOSK ERROR] " + e.Data);
                };

                bool started = voskProcess.Start();

                if (!started)
                {
                    MessageBox.Show("Failed to start Vosk listener.");
                    return;
                }

                voskProcess.BeginOutputReadLine();
                voskProcess.BeginErrorReadLine();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error starting Vosk listener:\n" + ex.Message);
            }
        }

        // ------------------------------------------------------------
        // READ TEXT COMMAND GENERATED BY VOSK
        // ------------------------------------------------------------
        private void StartVoiceMonitor()
        {
            voiceTimer = new DispatcherTimer();
            voiceTimer.Interval = TimeSpan.FromMilliseconds(200);
            voiceTimer.Tick += ReadVoiceCommand;
            voiceTimer.Start();
        }

        private void ReadVoiceCommand(object sender, EventArgs e)
        {
            if (!File.Exists(voiceCommandFile)) return;

            string text;
            try
            {
                text = File.ReadAllText(voiceCommandFile).Trim().ToLower();
            }
            catch { return; }

            if (string.IsNullOrWhiteSpace(text)) return;

            // Clear AFTER reading
            File.WriteAllText(voiceCommandFile, "");

            // Speech Commands
            if (text.Contains("login"))
                LoginButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));

            else if (text.Contains("signup") || text.Contains("sign up"))
                SignUpButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));

            else if (text.Contains("close"))
                this.Close();

            else if (text.Contains("minimize") || text.Contains("minimise"))
                WindowState = WindowState.Minimized;

            else if (text.Contains("full screen"))
                MaximizeButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
        }

        // ------------------------------------------------------------
        // OPEN NEW WINDOWS
        // ------------------------------------------------------------
        private void LoginButton_Click(object sender, RoutedEventArgs e)
        {
            new LoginWindow().Show();
            this.Close();
        }

        private void SignUpButton_Click(object sender, RoutedEventArgs e)
        {
            new SignUpWindow().Show();
            this.Close();
        }

        private void CloseButton_Click(object sender, RoutedEventArgs e) => this.Close();

        private void MinimizeButton_Click(object sender, RoutedEventArgs e)
        {
            WindowState = WindowState.Minimized;
        }

        private void MaximizeButton_Click(object sender, RoutedEventArgs e)
        {
            if (isMaximized)
            {
                WindowState = WindowState.Normal;
                Width = 900;
                Height = 600;
                isMaximized = false;
            }
            else
            {
                WindowState = WindowState.Maximized;
                isMaximized = true;
            }
        }

        // ------------------------------------------------------------
        // WINDOW CLOSE — DO NOT KILL VOSK EXE
        // ------------------------------------------------------------
        private void Window_Closed(object sender, EventArgs e)
        {
            voiceTimer?.Stop();
        }

        // ------------------------------------------------------------
        // UI ANIMATION
        // ------------------------------------------------------------
        private void SetupButtonAnimations(Button b)
        {
            var scale = new ScaleTransform(1, 1);
            b.RenderTransformOrigin = new Point(0.5, 0.5);
            b.RenderTransform = scale;

            b.MouseEnter += (s, e) =>
            {
                var a = new DoubleAnimation(1, 1.1, TimeSpan.FromMilliseconds(180));
                scale.BeginAnimation(ScaleTransform.ScaleXProperty, a);
                scale.BeginAnimation(ScaleTransform.ScaleYProperty, a);
            };

            b.MouseLeave += (s, e) =>
            {
                var a = new DoubleAnimation(1.1, 1, TimeSpan.FromMilliseconds(180));
                scale.BeginAnimation(ScaleTransform.ScaleXProperty, a);
                scale.BeginAnimation(ScaleTransform.ScaleYProperty, a);
            };
        }
    }
}
